import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ModalDisp from '../components/courelistmodal'
import Card from 'react-bootstrap/Card';
import Badge from 'react-bootstrap/Badge';


export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Academics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

          
        <h1 className={styles.title}>Academic Summary</h1>
        <h3 className={styles.code}>My MIT Journey - 2021 through 2025</h3>
        <div className={styles.academicslanding}></div>

        <div className={styles.container}>
          


            <div className="text-center">
                <br/>
                <h2>Academic Summary</h2>
                <ModalDisp className="text-center"></ModalDisp>
                

                
                <Card>
                    <Card.Body>Cumulative MIT GPA: 4.5</Card.Body>
                </Card>

            </div>
        </div>
        <br /><br />
        <div className="container text-left">
            <h2>
                Massachusetts Institute of Technology (MIT) <Badge bg="secondary">B.S. Aerospace Engineering, 2025</Badge>
            </h2>
            
            
                I graduated with High Honors from Daytona State College as a dual enrollment student in high school. 
                Courses included:
                <ul>
                    <li>Calculus I, II, III</li>
                    <li>Differential Equations</li>
                    <li>Physics with Calculus I, II</li>
                </ul>
                <Card>
                    <Card.Body>Cumulative GPA: 4.0</Card.Body>
                </Card>
            

            <br /><br />
            <h2>
                UROP Research Experience <Badge bg="secondary">Oct 2021- May 2022</Badge>
            </h2>
            
            I worked as an undergraduate researcher in the Department of Aeronautics and Astronautics at MIT.

            Relevant areas:
            <ul>
                <li>Prototyping in XPlane 11</li>
                <li>MATLAB Scripting</li>
                <li>Git Version Control</li>
                <li><a href="https://Electra.aero">Electra</a> - electric short takeoff and landing vehicle (eSTOL) urban air mobility technology</li>
            </ul>
            What is my role? 

            → I applied my aeronautical knowledge and experience to designing the cockpit for an entirely new and experimental aircraft. Due to the blown lift aerodynamics of the electra eSTOL vehicle, the approach and departure paths are significantly steeper than a traditional aircraft. I worked with a team of PhDs and MIT faculty to propose the visual elements, instrumentation/avionics layout, and UI design in the simulator before the technical demonstrator is built for real-world testing.

            I have a passion for the urban mobility sector and I am fascinated by the idea of electric air taxis replacing inefficient modes of transportation today.
            
            <br /><br />
            <h2>
                Daytona State College <Badge bg="secondary">A.A., 2021</Badge>
            </h2>
            
            
                I graduated with High Honors from Daytona State College as a dual enrollment student in high school. 
                Courses included:
                <ul>
                    <li>Calculus I, II, III</li>
                    <li>Differential Equations</li>
                    <li>Physics with Calculus I, II</li>
                </ul>
                <Card>
                    <Card.Body>Cumulative GPA: 4.0</Card.Body>
                </Card>
            

        </div>

        
      </main>

      
    </div>
  )
}
