import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Table from 'react-bootstrap/Table';
import Card from 'react-bootstrap/Card';
import Alert from 'react-bootstrap/Alert';
import Badge from 'react-bootstrap/Badge'
import Button from 'react-bootstrap/Button'

import teachingImg from '../public/images/teaching.jpeg'
import flyingImg from '../public/images/gulfstream.jpeg'


export default function Aviation() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aviation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

          
        <h1 className={styles.title}>Aviation Overview</h1>
        <h3 className={styles.code}>My journey in flight.</h3>
        <div className={styles.aviationlanding}></div>
        <div className={styles.container}>
          


            <div className="text-center">
                <br></br>
                <h2>Aviation Overview</h2>
                

            </div>
        </div>
        <br /><br />
        <div className="container row text-left sides">
            <div className="col-sm">
            <h2>
                Certificates and Qualifications
            </h2>
           
            Certificates and Ratings:
            <ul>
                <li>Airline Transport Pilot - AMEL</li>
                <li>Airbus A-320 Type Rating</li>
                <li>Airline Transport Pilot - ASEL</li>
                <li>Cirrus Vision Jet SF50 Type Rating</li>
                <li>Certified Flight Instructor (CFI) - Single Engine</li>
                <li>Certified Flight Instructor (CFII) - Instrument</li>
                <li>Certified Flight Instructor (MEI) - Multi Engine</li>
                <li>Gold Seal Flight Instructor</li>
            </ul>
            
                <Table striped bordered hover variant="dark">
                    <thead>
                        <tr>
                            <th>Total Time: 1558</th>
                            <th>Instrument: 180</th>
                            <th>Dual Given: 950</th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td>Multi Engine: 67</td>
                            <td>High Perf: 210</td>
                            <td>Pilot in Command: 1486</td>
                        </tr>
                    </tbody>
                </Table>
                <Alert key={'primary'} variant={'primary'}>
                    Update: I am operating the SF50 Vision Jet based out of the Boston area as of January 2025.
                </Alert>
            </div>
            <div className="col-sm-3">
               
                  <Image 
                  className="img img-responsive imgcasing" 
                  src={teachingImg} 
                  layout="intrinsic"
                  style={{"border": "0.3vh solid blue"}}
                  
                  />
                
            </div>

            
        </div>
        <br /><br />
        <div className="container">
        <h2 className="text-center">Aviation Work Experience</h2>



            <div className="bg-dark text-white row" style={{margin:"3vh"}}>
                <div className="col-sm" style={{padding:"3vh"}}>
                    <h3>FlyHdg360   <Badge>Aug 2021 - Present</Badge></h3>

                        I am qualified as a Cirrus Vision Jet SF50 Captain and offer professional pilot services through my company, FlyHdg360. I also hold
                        a gold seal CFI certificate and provide instruction for private clients in the Boston area. 
                        <ul>
                            <li>Manage and direct aircraft operations for private clients.</li>
                            <li>Provide Vision Jet Captain services.</li>
                            <li>Work as an experienced flight instructor towards all certificate and rating levels.</li>
                        </ul>
                </div>

                <div className="col-sm" style={{padding:"3vh"}}>
                    <strong>Address:</strong><br />
                    Cambridge, MA 02139<br /><br />
                    <Button target="_blank" href="https://flyhdg360.com">Website</Button>
                    <br /><br />
                    Role: President <br /><br />
                    <Button target="_blank" style={{marginLeft: "2vh"}} href="mailto:grayson@flyhdg360.com">Email FlyHdg360</Button>
                </div>

            </div>
            
            <div className="bg-dark text-white row" style={{margin:"3vh"}}>
                <div className="col-sm" style={{padding:"3vh"}}>
                    <h3>AeroCharterNE   <Badge>Sept 2023 - Present</Badge></h3>

                        I contract to operate part 91 flights in the Piper Navajo and King Air E90.
                        <ul>
                            <li>Conduct all weather flight operations in high performance multi engine aircraft.</li>
                            <li>Provide outstanding customer service to clients.</li>
                        </ul>
                </div>

                <div className="col-sm" style={{padding:"3vh"}}>
                    <strong>Address:</strong><br />
                    265 Fruit St <br />
                    Mansfield, MA 02048<br /><br />
                    <Button target="_blank" href="https://avierflight.com">Website</Button>
                    <br /><br />
                    Supervisor: Mitch Roberts, President <br /><br />
                    <Button target="_blank" style={{marginLeft: "2vh"}} href="mailto:mroberts@aerocharterne.com">Email Supervisor</Button>
                </div>

            </div>

            <div className="bg-dark text-white row" style={{margin:"3vh"}}>
                <div className="col-sm" style={{padding:"3vh"}}>
                    <h3>Avier Flight School   <Badge>Jan 2022 - Jan 2024</Badge></h3>

                        I worked as a CFII/MEI at Avier Flight School, teaching the following flight training courses:
                        <ul>
                            <li>Private Pilot</li>
                            <li>Instrument Rating</li>
                            <li>Commercial Pilot</li>
                            <li>Certified Flight Instructor + CFII/MEI</li>
                        </ul>
                </div>

                <div className="col-sm" style={{padding:"3vh"}}>
                    <strong>Address:</strong><br />
                    47 LP Henderson Rd. <br />
                    Beverly, MA 01915<br /><br />
                    <Button target="_blank" href="https://avierflight.com">Website</Button>
                    <br /><br />
                    Supervisor: Paul Beaulieu, Owner <br /><br />
                    <Button target="_blank" href="tel:9788939513">Call Avier</Button>
                    <Button target="_blank" style={{marginLeft: "2vh"}} href="mailto:paul@avierflight.com">Email Supervisor</Button>
                </div>

            </div>

            <div className="bg-dark text-white row" style={{margin:"3vh"}}>
                <div className="col-sm" style={{padding:"3vh"}}>
                    <h3>Gulfstream Aerospace   <Badge>May 2022 - Aug 2022</Badge></h3>

                        I wored as a flight operations intern for Gulfstream Flight Operations. I: 
                        <ul>
                            <li>Worked to enhance processes and methods within Gulfstream Flight Operations</li>
                            <li>Utilized Python and Power BI to analyze and present meaningful insights to leadership</li>
                            <li>Applied technical skills to automate out of date scheduling and approvals processes</li>
                            <li>Learned from the best on the corporate aviation industry</li>
                        </ul>
                </div>

                <div className="col-sm" style={{padding:"3vh"}}>
                    <strong>Address:</strong><br />
                    500 Gulfstream Road <br />
                    Savannah, GA 31408<br /><br />
                    <Button target="_blank" href="https://gulfstream.com">Website</Button>
                    <br /><br />
                    Supervisor: Brandon Lundy, Flight Operations Supervisor <br /><br />
                    <Button target="_blank" href="mailto:brandon.lundy@gulfstream.com">Email Supervisor</Button>
                </div>

            </div>

            <div className="bg-dark text-white row" style={{margin:"3vh"}}>
                <div className="col-sm" style={{padding:"3vh"}}>
                    <h3>FlyCorps Aviation   <Badge>May 2022 - Aug 2022</Badge></h3>

                        I wored as a flight instructor (CFI-I) for FlyCorps while in Savannah for the summer.
                        <ul>
                            <li>Taught IFR and CPL courses</li>
                            <li>Earned CMEL and MEI add-on ratings</li>
                        </ul>
                </div>

                <div className="col-sm" style={{padding:"3vh"}}>
                    <strong>Address:</strong><br />
                    100 Eddie Jungemann Dr <br/>Savannah, GA 31408<br /><br />
                    <Button target="_blank" href="https://flycorps.com">Website</Button>
                    <br /><br />
                    Supervisor: Jake Becker, Owner <br /><br />
                    <Button target="_blank" href="mailto:jake@flycorps.com">Email Supervisor</Button>
                </div>

            </div>
            
            
         


        </div>

        <div className="container">

            <Image 
            src={flyingImg}
            layout="intrinsic"
            style={{"border": "0.3vh solid blue"}}
            className="img img-responsive"
            
            />
        </div>
         

  

        
      </main>

    
    </div>
  )
}
