import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Table from 'react-bootstrap/Table';
import Card from 'react-bootstrap/Card';
import Alert from 'react-bootstrap/Alert';
import Badge from 'react-bootstrap/Badge'
import Button from 'react-bootstrap/Button'

import zingImg from '../public/images/zing3.jpeg'
import flyhdg360 from '../public/images/flyhdg360.jpeg'
import gav from '../public/images/gav.jpeg'


export default function Entrepeneurship() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Entrepeneurship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

          
        <h1 className={styles.title}>Entrepeneurship</h1>
        <h3 className={styles.code}>Not the usual stuff.</h3>
        <div className={styles.entrepeneurshiplanding}></div>
        <div className={styles.container}>
          


            <div className="text-center">
                <br></br>
                <h2>Startups Overview</h2>
                

            </div>
        </div>
        <br /><br />
        <div className="container row text-left sides bg-light" style={{padding: "2vh"}}>

            <div className="col-sm-3">
                
                <Image 
                className="img img-responsive imgcasing" 
                src={zingImg} 
                layout="intrinsic"
                style={{"border": "0.3vh solid blue"}}
                
                />
                
            </div>
            <div className="col-sm">
            <h2>
                Zing Drone Solutions
            </h2>

            <h5>
                I have been a part of <strong>Zing Drone Solutions </strong> since 2020. I joined as 
                <em> Head of Flight Operations </em> and was promoted to <em>Chief Operating Officer (COO) </em> 
                in January, 2022. Since I joined, Zing has raised about <strong>$250,000</strong> in funding. 
                My role includes managing our FAA Part 107 Category and Part 135 certification efforts, brainstorming
                with the core team, business analytics/strategy, and to act as an in-house technical aerospace 
                expert.
                <br /><br />
                <Button href="https://wefunder.com/zing" target="_blank">Zing's WeFunder Campaign - Closed April 2022</Button>
                <Button href="https://zingdrones.com/" style={{marginLeft: "3vh"}} target="_blank">Zing's Website</Button>

            </h5>
           
                <Alert key={'warning'} variant={'warning'}>
                    Zing will raise a seed funding round starting Q4 of 2022!
                </Alert>
            </div>
             
        </div>

        <div className="container row text-left sides bg-light" style={{marginTop: "5vh", padding: "2vh"}}>

            
            <div className="col-sm" >
            <h2>
                FlyHdg360
            </h2>

            <h5>
                I started <strong>FlyHdg360 </strong> in 2021 after becoming a CFI. I still utilize FlyHdg360 
                to work as an independant flight instructor, provide checkride prep services, 
                teach with the Tech Flight Corps (nonprofit), and generate material.
                <br /><br />
                <Button href="https://flyhdg360.com/" target="_blank">Website</Button>

            </h5>
           
            </div>
            <div className="col-sm-3">
                
                <Image 
                className="img img-responsive imgcasing" 
                src={flyhdg360} 
                layout="intrinsic"
                style={{"border": "0.3vh solid blue"}}
                
                />
                
            </div>
             
        </div>

        <div className="container row text-left sides bg-light" style={{marginTop: "5vh", padding: "2vh"}}>

            <div className="col-sm-4">
                
                <Image 
                className="img img-responsive imgcasing" 
                src={gav} 
                layout="intrinsic"
                style={{"border": "0.3vh solid blue"}}
                
                />
                
            </div>
            <div className="col-sm">
            <h2>
                Gray AerialVisual
            </h2>

            <h5>
                I started <strong>Gray AerialVisual </strong> at the age of 12 with help from my parents. Initially, 
                I was most interested in aerial photography with drones. I later added website development and 
                marketing to my services. When I turned 16, I earned my <strong>FAA Part 107 certificate </strong> and began operating 
                on my own for a variety of real estate and misc clients in the Volusia County Area. 
                <br /><br />
                <Button href="https://grayaerialvisual.com/" target="_blank">Website</Button>

            </h5>
     
            </div>
             
        </div>


        <br /><br />
        <div className="container">
        <h2 className="text-center">Misc Work Experience</h2>

            <div className="bg-dark text-white row" style={{margin:"3vh"}}>
                <div className="col-sm" style={{padding:"3vh"}}>
                    <h3>Georgian Inn Beach Club   <Badge>March 2020 - Aug 2021</Badge></h3>

                        I worked as the Software Administrator at GIBC. My role included: 
                        <ul>
                            <li>Finding and implementing a new property management system</li>
                            <li>Creating a new website for the Georgian Inn</li>
                            <li>Working with software service providers to develop a custom booking solution</li>
                            <li>Training and monitoring rollout on site</li>
                        </ul>
                </div>

                <div className="col-sm" style={{padding:"3vh"}}>
                    <strong>Address:</strong><br />
                    759 S Atlantic Ave<br /> Ormond Beach, FL 32176<br /><br />
                    <Button target="_blank" href="https://gi-bc.com">Website</Button>
                    <br /><br />
                    Supervisor: Marty Young, General Manager <br /><br />
                    <Button target="_blank" href="mailto:gm@gi-bc.com">Email Supervisor</Button>
                </div>

            </div>


        </div>
         

  

        
      </main>

    
    </div>
  )
}
