import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Button from 'react-bootstrap/Button';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Grayson Bertaina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      
        <h1 className={styles.title}>
          Grayson Bertaina
        </h1>
        <h3 className={styles.code}>MIT AeroAstro, Flight Instructor (CFII/MEI), Entrepeneur, Adventuerer.</h3>


        <div className={styles.landing}></div>
        <p className={styles.description}>
          Browse my portfolio below!
          
        </p>

        <div className={styles.grid}>
          <Link href="/academics"><a className={styles.card}>
            <h2>Academics &rarr;</h2>
            <p>
              MIT '25 AeroAstro
              
            </p>
          </a></Link>

          <Link href="/aviation"><a className={styles.card}>
            <h2>Aviation &rarr;</h2>
            <p>
              CFI/CFII/MEI, CPL
            </p>
          </a></Link>

          <Link href="/entrepeneurship"><a className={styles.card}>
            <h2>Entrepeneurship &rarr;</h2>
            <p>
              Founder and COO
            </p>
          </a></Link>

        </div>
        <br /><br /><br /><br />
        <div className={styles.container}>
          <h1 style={{textAlign: "center"}}>Documents</h1>


          <div className={styles.grid}>

            <a href="https://s3.us-west-2.amazonaws.com/secure.notion-static.com/7cba564e-1066-440c-83d4-dd9da9106184/GraysonBertainaresume.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220823%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220823T003942Z&X-Amz-Expires=86400&X-Amz-Signature=d2cf6e8ed09474f3572c02d9a7e0c33f55384fb8ac161fbd4fabeef449eac8a6&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22GraysonBertainaresume.pdf%22&x-id=GetObject" download className={styles.card}>
              <div>
                <h3>Resume</h3>
                <Button variant="outline-primary">Download</Button>
              </div>
            </a>

            <a href="../public/diploma.pdf" className={styles.card}>
              <div >
                <h3>Pilot Certificates</h3>
                <Button variant="outline-primary">Download</Button>
              </div>
            </a>

            



          </div>

        

        </div>
        <br /><br />
        <embed src="https://s3.us-west-2.amazonaws.com/secure.notion-static.com/7cba564e-1066-440c-83d4-dd9da9106184/GraysonBertainaresume.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220823%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220823T003942Z&X-Amz-Expires=86400&X-Amz-Signature=d2cf6e8ed09474f3572c02d9a7e0c33f55384fb8ac161fbd4fabeef449eac8a6&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22GraysonBertainaresume.pdf%22&x-id=GetObject" 
          width="80%" height="800"
          type="application/pdf"></embed>

        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
