import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Button from 'react-bootstrap/Button';



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Grayson Bertaina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      
        <h1 className={styles.title}>
          Grayson Bertaina
        </h1>
        <h3 className={styles.code}>MIT AeroAstro, Professional Pilot (ATP/CFII), Entrepeneur, Adventuerer.</h3>


        <div className={styles.landing}></div>
        <p className={styles.description}>
          Browse my portfolio below!
          
        </p>

        <div className={styles.grid}>
          <Link href="/academics"><a className={styles.card}>
            <h2>Academics &rarr;</h2>
            <p>
              MIT '25 AeroAstro
              
            </p>
          </a></Link>

          <Link href="/aviation"><a className={styles.card}>
            <h2>Aviation &rarr;</h2>
            <p>
              CFI/CFII/MEI, CPL
            </p>
          </a></Link>

          <Link href="/entrepeneurship"><a className={styles.card}>
            <h2>Entrepeneurship &rarr;</h2>
            <p>
              Founder and COO
            </p>
          </a></Link>

          <Link href="/services"><a className={styles.card}>
            <h2>Services &rarr;</h2>
            <p>
              Grayson's Services
            </p>
          </a></Link>

        </div>
        <br /><br /><br /><br />
        <div className={styles.container}>
          <h1 style={{textAlign: "center"}}>Documents</h1>


          <div className={styles.grid}>

            <a href="https://drive.google.com/file/d/1NPqAhUBlsqbHDWn6oN86q8WVAHC3Tf38/view?usp=sharing" download className={styles.card}>
              <div>
                <h3>Resume</h3>
                <Button variant="outline-primary">Download</Button>
              </div>
            </a>

            <a href="https://drive.google.com/file/d/1TVUrJ1EpsoaL2GxKJMKtWoLz0Tb5X2Ah/view?usp=sharing" download className={styles.card}>
              <div >
                <h3>Pilot Certificates</h3>
                <Button variant="outline-primary">Download</Button>
              </div>
            </a>

            <a></a>



          </div>

        

        </div>
        <br />

        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
